### ISSUE TITLE
Please use the hyf-homework repo, not the template

### ISSUE THREAD

**Issue by chklueter** [MirSzabo/hyf-homework#1]
Hi @MirSzabo 

Well done on being on top of homework - but you started pushing it to `hyf-homework-template` - that creates a bit of confusion for us when we check for homework.

Please push the files to e.g. `/hyf-homework/javascript/week2` instead :)) 

The reason for this is multifold - you get less green "activity" points on GitHub when committing in a forked repo, we can't create `issues` in it, and we also lose the (easy) overview of what you've been working on. :)

**Comment by MirSzabo** [comment]
oh :/
sorry for confusion I will continue as you wrote
