### ISSUE TITLE
Homework js2 week 3

### ISSUE THREAD

**Issue by mogenshoj** [MirSzabo/hyf-homework#2]
**warmup**
Good job! Nice one with the Google Maps API 🗺 
Some minor things.

Watch the syntax, e.g.:
`logOutButton.addEventListener("click", () => {logOut(5, "5 seconds after button is clicked")});`

should be:
```
logOutButton.addEventListener("click", () => {
  logOut(5, "5 seconds after button is clicked")
});
```

Watch the indention, e.g.:
```
function getLocation(){
    navigator.geolocation.getCurrentPosition(function(position) {
    console.log(`This is the latitude ${position.coords.latitude}`)
    console.log(`This is the longitude ${position.coords.longitude}`)
  });
}
```

should be:
```
function getLocation(){
    navigator.geolocation.getCurrentPosition(function(position) {
        console.log(`This is the latitude ${position.coords.latitude}`)
        console.log(`This is the longitude ${position.coords.longitude}`)
  });
}
```

You should pass in the functions as arguments, but close enough :)
```
function jokeCreator(shouldTellFunnyJoke, logFunnyJoke, logBadJoke) {
    function logFunnyJoke(){
        console.log("Question: How long does the loop last? Answer: For a while");
    };
    function logBadJoke(){
        console.log("Want to hear a javascript joke? I'll callback later.");
    };

    if(shouldTellFunnyJoke){
        logFunnyJoke();
    }
    else{
        logBadJoke();
    }
}
jokeCreator(true);
jokeCreator(false);
```

**game**
Nice design :) Very clean code, nice to read.
Some small things.

When you check for `true`, you can just check the variable without `===`
` if (clicked === true && keyValue === "l") {`

Like:
` if (clicked && keyValue === "l") {`

For this block here:
```
  if (counterS.innerHTML === "" && counterL.innerHTML === "" && time === "") {
    winnerL.textContent = "";
    winnerS.textContent = "";
  } else if (counterS.innerHTML === "" && counterL.innerHTML === "") {
    ...
```
It would be preferred to check the count variables (where you stored the counted value) instead of the using the DOM elements (`innerHTML`)

Something like:
`if (countS === 0 && countL === 0 && time === "") {`

Where does `this.dataset` come from?
`const time = (parseInt(this.dataset.time));` 🤔 

**hyfBay**
Nice one!

**Comment by MirSzabo** [comment]
thanks for detailed comments!
I corrected indention in warmup task
in game task this.dataset I saw in one tutorial and it is not working without this code

**Comment by mogenshoj** [comment]
ah i see. I found it (never used this syntax before). It refers to the `data-time` attributes you put on the html buttons. Here: https://github.com/MirSzabo/hyf-homework/blob/master/javascript/javascript2/week3/fastest_presser/index.html#L15

So it is fine 👍
