### ISSUE TITLE
JS2 Week 2 Feedback

### ISSUE THREAD

**Issue by orhantoy** [MirSzabo/hyf-homework#3]
@MirSzabo :v:

## Warmup array exercises / Doubling of number

👍 Nice solution.

## Warmup array exercises / Working with movies

Nice work here! 💪 I especially like the dropdown that makes it easier to inspect your homework.

- **Exercise 4:** You almost have the right solution here. There are 2 issues: `movieDatabaseWithTag` is an array of arrays but should actually be an array of objects. One hint I can give is that you should not return `movies` at the end. Another (smaller) issue is that setting `movie.tag` will actually modify the objects in `movies`. Try looking into how you can copy/duplicate an object instead.
  https://github.com/MirSzabo/hyf-homework/blob/ba7f70f4595c7558ead7ee1759887407ed4c357a/javascript/javascript2/week2/movies/movies_my_code.js#L25-L36
- **Exercise 7:** Not sure I fully understand why you need a regex in this exercise. A simpler approach would be to split the title by space and then check for duplicates in that list of words. Another thing is that the exercise states that "Create an array of movies where ..." but what you're returning is an array of the titles.
  https://github.com/MirSzabo/hyf-homework/blob/ba7f70f4595c7558ead7ee1759887407ed4c357a/javascript/javascript2/week2/movies/movies_my_code.js#L67-L86
- I'll be skipping the optional exercises as we're behind with giving feedback, sorry about this.
- Overall though very nice work 👍 

## hyfBay - get the okay'est products here - continued

Also, very nice work here! I noticed the search is case sensitive so when searching for "car" no results show up even though "Car" works. Not a big deal but something to consider for improving and making more user friendly.

**Comment by MirSzabo** [comment]
hello, thank you for checking my code I will try to correct the mistakes
I think I got your points 👍
and thank you for nice feedback!

**Comment by orhantoy** [comment]
- The updates to Exercise 4 looks good, nice work 👍 
- Exercise 7 is still not entirely correct. The exercise states that "Create an array of movies where ..." but what you're returning is an array of the titles. But I think your solution is acceptable, so don't worry about it.

I'll mark your assignment as approved ✅
